services:
  prometheus:
    image: prom/prometheus:v3.5.0
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 15s
      timeout: 3s
      retries: 5
  node-exporter:
    image: prom/node-exporter:v1.9.1
    restart: unless-stopped
    ports:
      - 9100:9100
    privileged: true
    networks:
      - network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9100/metrics"]
      interval: 15s
      timeout: 3s
      retries: 5
  grafana:
    image: grafana/grafana:12.1.1
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 15s
      timeout: 3s
      retries: 5
    depends_on:
      prometheus:
        condition: service_healthy
networks:
  network:
    driver: bridge
volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
