services:
  prometheus:
    image: prom/prometheus:v3.3.0
    restart: on-failure
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - network
  grafana:
    image: grafana/grafana:11.6.0
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - network
networks:
  network:
    driver: bridge
volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
