services:
  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: prometheus
    restart: on-failure
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:11.1.4
    container_name: grafana
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge
volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
